import "./globals.css"; 
import HeaderShell from "../components/HeaderShell";
import Footer from "../components/Footer";

export const metadata = {
  title: "CarrerCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="cc-body">
        <HeaderShell />
        <main className="cc-main">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
